name: Bug Report
description: Report a bug or issue with the platform
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true

  - type: dropdown
    id: service
    attributes:
      label: Affected Service
      description: Which service is affected?
      options:
        - n8n (Workflows)
        - Directus (CMS)
        - Chatwoot (Messaging)
        - Docker/Infrastructure
        - Claude AI Integration
        - WhatsApp/Facebook Channel
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System down)
        - High (Major feature broken)
        - Medium (Feature impaired)
        - Low (Minor issue)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Include any error logs or screenshots
      placeholder: Paste logs here...
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Include relevant environment details
      placeholder: |
        - Docker version:
        - OS:
        - RAM:
