name: Task
description: Create a task or work item
title: "[Task]: "
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        Create a new task for the project.

  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: What needs to be done?
      placeholder: Describe the task...
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know this task is complete?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of task is this?
      options:
        - Infrastructure
        - Workflow Development
        - Integration
        - Documentation
        - Testing
        - Maintenance
        - Other
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Does this task depend on other issues?
      placeholder: "Depends on #123, #456"

  - type: textarea
    id: notes
    attributes:
      label: Technical Notes
      description: Any technical details or implementation notes?
